// <auto-generated />
namespace UniversityCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v2_Enabled_Students : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_Enabled_Students));
        
        string IMigrationMetadata.Id
        {
            get { return "202012010015451_v2_Enabled_Students"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
