// <auto-generated />
namespace UniversityCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v3_Enabled_OfficeAssignments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3_Enabled_OfficeAssignments));
        
        string IMigrationMetadata.Id
        {
            get { return "202012010030426_v3_Enabled_OfficeAssignments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
